name = "neond00m/vide_typed"
version = "0.3.2-test.1"
description = "vide with types and camel case"
authors = ["centau"]
repository = "https://github.com/neond00m/vide"
license = "MIT"

includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src/**",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
